services:

  ignition:
    build:
      context: .
      args:
        IGNITION_VERSION: "8.3.9"

    container_name: ignition-maker

    restart: unless-stopped

    ports:
      - "8088:8088"
      - "8043:8043"
      - "8060:8060"

    environment:
      ACCEPT_IGNITION_EULA: "Y"

      IGNITION_EDITION: "maker"

      GATEWAY_ADMIN_USERNAME: "${IGNITION_ADMIN_USERNAME}"
      GATEWAY_ADMIN_PASSWORD: "${IGNITION_ADMIN_PASSWORD}"

      TZ: "America/Detroit"

    volumes:
      - ignition-data:/usr/local/bin/ignition/data

    command:
      - "-n"
      - "gcp-ignition-maker"

volumes:
  ignition-data: